name: symfony-vue-example

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.5'
        extensions: intl iconv ctype gd sodium zip
        coverage: none # Disables Xdebug by default for faster test execution

    - name: Get Composer Cache Directory
      id: composer-cache
      working-directory: backend/
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v5
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      working-directory: backend/
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Execute Unit tests
      working-directory: backend/
      run: ./bin/phpunit